config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  get 'home/welcome'
  get 'login',     to: 'sessions#new', as: 'login'
  get 'service',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount Simditor::Engine => '/simditor'

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :topics
      get :comments
      get :notifications
    end
  end

  resources :nodes

  resources :topics, concerns: [:likeable] do
    get :search, on: :collection
    delete :trash, on: :member
  end

  resources :comments, concerns: [:likeable] do
    delete :trash, on: :member
  end

  root "home#welcome"

  draw :admin
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Trashable
  include Likeable
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  scope :recent, -> {order(created_at: :desc)}
  scope :hot, -> {where("topics.comments_count >= ?", 50 )}
  scope :timeliness, -> {where(created_at: 1.month.ago..Time.now)} #时效性

  belongs_to :user, counter_cache: true, touch: true
  belongs_to :node, counter_cache: true, touch: true

  has_many :comments, as: :commentable, dependent: :destroy

  after_trash   :decrement_counter_cache
  after_restore :increment_counter_cache
  after_destroy :increment_counter_cache, if: :trashed?

  class << self
    def excellent #精华帖

    end
  end

  def increment_counter_cache
    if node.has_attribute? :topics_count
      node.class.update_counters node.id, topics_count: 1
    end
  end

  def decrement_counter_cache
    if node.has_attribute? :topics_count
      node.class.update_counters node.id, topics_count: -1
    end
  end

  def first_comment
    comments.list.first
  end

  def second_comment
    comments.list.second
  end

  def third_comment
    comments.list.third
  end

  def last_comment
    Comment.find(last_comment_id)
  end

  private

  def self.search_with_es(*args)
    __elasticsearch__.search(*args)
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController
  before_action :find_topic, only: [:show, :edit, :update, :add_to_recycle, :set_top]
  def index
    @admin_topics_grid = TopicsGrid.new(params[:topics_grid])
    @assets = @admin_topics_grid.assets.page(params[:page])
  end

  def show
    if @topic != nil
      @comments = @topic.comments
    else
      @topic = Topic.with_trashed.find(params[:id])
    end
  end

  def recycle_topic
    @recycle_topic = RecycleTopicGrid.new(params[:recycle_topic_grid])
    @assets = @recycle_topic.assets.page(params[:page])
  end

  def add_to_recycle
    if @topic != nil
      @topic.update(:is_trashed => true)
      @a = 0
    else
      @topic = Topic.with_trashed.find(params[:id])
      @topic.update(:is_trashed => false)
      @a = 1
    end
    if @topic.save
      if @a == 0
        redirect_to admin_topics_path
      else
        redirect_to admin_recycle_list_path
      end
    else
      if @a == 1
        redirect_to admin_topics_path
      else
        redirect_to admin_recycle_list_path
      end
    end
  end

  def topic_top
    if @topic.level != 4
      @topic.update(:level => 4)
    else
      @topic.update(:level => nil)
    end
  end

  def topic_good
    if @topic.level != 3
      @topic.update(:level => 3)
    else
      @topic.update(:level => nil)
    end
  end

  def trash_all

    locked = params[:locked]

    if params[:topic_ids]
      ids = params[:topic_ids].split(",")

      ids.each do |id|
        topic = Topic.find_by(id: id)
        user = topic.try(:user)
        topic.try(:trash)

        current_user.set_lock(user) if locked == "true"
      end
    end

    render json: {status: :ok }
  end

  private

  def find_topic
    @topic = Topic.find_by(id: params[:id])
  end

  def topic_params
    params.require(:topic).permit!
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource

  before_action :node_list
  before_action :login_required, :no_locked_required, except: [:index, :show, :search]
  before_action :set_topic, except: [:index, :new, :create, :search]

# 未添加权限
  def index
    @title_list = Node.list.pluck(:title)

    if params[:node_id]
      @node = Node.find(params[:node_id])

      @topics = @node.topics.recent.page(params[:page])
    elsif params[:level]
      @topics = Topic.where(level: params[:level]).recent.page(params[:page])
    else
      @topics = Topic.order("level DESC", "created_at DESC").page(params[:page])
    end
  end

  def show
    @topic.update(views: (@topic.views.to_i + 1))
    @topic_user = @topic.user
    @first_comment = @topic.first_comment
    @second_comment = @topic.second_comment
    @comments = @topic.comments.recent.page(params[:page])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render action: :edit
    end
  end

  def destroy
    @topic.destroy

    redirect_to topics_path
  end

  def trash
    @topic.trash

    redirect_to topics_path
  end

  def search
    @topics = Topic.search_with_es(
      query: {
        multi_match: {
          query: params[:q].to_s,
          fields: ['title', 'body']
        }
      }
    ).records
  end

  private

  def node_list
    @nodes = Node.list
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit!
  end

end

app/views/topics/_form.html.erb
      <%= form_for @topic do |f|%>
        <h3>发布新帖</h3>
        <div class="post-item">
          <span class="title">标题</span>
          <%= f.text_field :title, class: :con, placeholder: "请输入帖子标题"  %>
        </div>
        <div class="post-item">
          <span class="title">帖子分类</span>
          <div class="con">
            <div class="select-title">
              <%= f.select :node_id, Node.all.map { |c| [c.title, c.id] }%>
            </div>
          </div>
        </div>

        <% if is_admin? %>
          <div class="post-item">
            <span class="title">关键字</span>
            <div class="con">
              <%= f.text_field :seo_keyword %>
              <p class="tips">输入帖子内容的关键字， 以“,”分开</p>
            </div>
          </div>
        <% end %>

        <div class="post-item">
          <span class="title">帖子内容</span>
          <div class="con">
            <%= f.text_area :body, simditor: true %>
            <%= f.submit "发布新帖", class:"btn"%>
          </div>
        </div>
      <% end %>

app/views/topics/edit.html.erb
<link rel="stylesheet" href="/kkb/new_post.css">
<div class="main">
  <%= render 'form' %>
</div>

app/views/topics/index.html.erb
<link rel="stylesheet" href="/kkb/index.css">

    <div class="main">
      <div class="left">
        <div class="post-list">
          <div class="title">
            <h3>全部帖子</h3>
            <ul class="tags">
              <li>
                <%= link_to "精品帖子", topics_path(:level => 3)%>
              </li>
              <li>
                <%= link_to "热门帖子", topics_path(:level => 2)%>
              </li>
              <li>
                <%= link_to "最新帖子", topics_path %>
              </li>
            </ul>
          </div>
          <div class="best list">
            <%= render "/shared/topic_list", collection: @topics %>
          </div>
        </div>
        <div class="page">
          <%= paginate @topics %>
        </div>
      </div>
      <div class="right">
        <%= render "/shared/search" %>
        <%= render "shared/topic_right" %>

        <div class="ad-img">
          <%= image_tag "mouse.jpg" %>
          <%= image_tag "mouse.jpg" %>
          <%= image_tag "mouse.jpg" %>
        </div>
      </div>
      <div class="sidebar">
        <dl>
          <dt>
            <a href="/">
              <%= image_tag "novice_help.png" %>
            </a>
          </dt>
          <dd>新手帮助</dd>
        </dl>
        <dl>
          <dt>
            <a href="">
              <%= image_tag "globle_feedback.png" %>
            </a>
          </dt>
          <dd>意见反馈</dd>
        </dl>
        <dl>
          <dt>
            <a href="/">
              <%= image_tag "return_to_top.png" %>
            </a>
          </dt>
          <dd>返回顶部</dd>
        </dl>
      </div>
    </div>

app/views/topics/new.html.erb
<link rel="stylesheet" href="/kkb/new_post.css">
<div class="main">
  <%= render 'form' %>
</div>

app/views/topics/search.html.erb
<link rel="stylesheet" href="/kkb/index.css">

    <div class="main">
      <div class="left">
        <div class="post-list">
          <div class="title">
            <h3>全部帖子</h3>
            <ul class="tags">
              <li><a href="javascript:;">精品帖子</a></li>
              <li><a href="javascript:;">热门帖子</a></li>
              <li><a href="javascript:;">最新帖子</a></li>
            </ul>
          </div>
          <div class="best list">
            <% @topics.each do |topic|%>
            <dl>
              <dt>
                <%= image_tag "head-img.gif" %>
              </dt>
              <dd class="post-name">
                <span class="tag-top">置顶</span>
                <span><%= link_to topic.title, topic_path(topic)%></span>
                <span class="tag-new">NEW</span>
                <span class="tag-best">精华</span>
                <span class="tag-mark">
                  <%= image_tag "mark.gif" %>
                </span>
              </dd>
              <dd class="post-info">
                <span><%= topic.user.name %></span><var>·</var>
                <span><%= format_datetime(topic.created_at) %></span><var>·</var>
                <span><%= topic.node.title %></span><var>·</var>
                <span>0浏览</span><var>·</var>
                <span><%= topic.comments_count %>回复</span>
              </dd>
              <% if is_admin? %>
                <dd class="choice">
                  <input name="check" type="checkbox">
                </dd>
              <% end %>
            </dl>
            <% end %>
            <!--  -->
            <% if is_admin? %>
              <div class="edit">
                <p class="choice">
                  <input class="check-all" type="checkbox">
                  <span>全选</span>
                </p>
                <ul class="edit">
                  <li>删除帖子</li>
                  <li>删除帖子，并封禁楼主3天</li>
                </ul>
              </div>
            <% end %>
          </div>
        </div>
        <div class="page">
          <%= paginate @topics %>
        </div>
      </div>
      <div class="right">
        <%= form_tag(search_topics_path, method: :get) do %>
          <%= text_field_tag :q, nil, class: 'search' %>
          <%= image_tag "search_icon.png", class: "search-bar" %>
        <% end %>

        <a href="<%= new_topic_path %>">
          <%= image_tag "new_topic.png", class: "new-topic" %>
        </a>

        <%= render "shared/topic_right" %>

        <div class="ad-img">
          <%= image_tag "mouse.jpg" %>
          <%= image_tag "mouse.jpg" %>
          <%= image_tag "mouse.jpg" %>
        </div>
      </div>
      <div class="sidebar">
        <dl>
          <dt>
            <a href="/">
              <%= image_tag "novice_help.png" %>
            </a>
          </dt>
          <dd>新手帮助</dd>
        </dl>
        <dl>
          <dt>
            <a href="">
              <%= image_tag "globle_feedback.png" %>
            </a>
          </dt>
          <dd>意见反馈</dd>
        </dl>
        <dl>
          <dt>
            <a href="/">
              <%= image_tag "return_to_top.png" %>
            </a>
          </dt>
          <dd>返回顶部</dd>
        </dl>
      </div>
    </div>

app/views/topics/show.html.erb
<%= content_for :title  do %>
  <%= @topic.title %>
<% end %>

<%= content_for :keywords do %>
  <%= @topic.seo_keyword %>
<% end %>

<link rel="stylesheet" href="/kkb/forum_detail.css">
    <div class="main">
      <div class="left">
        <div class="crumbs">
          <a href="/">论坛首页</a> >
          <a href="/"><%= @topic.node.title %></a>
        </div>
        <div class="post-list">
          <% if can? :trash, @topic %>
            <%= link_to "删除帖子", trash_topic_path(@topic), method: :delete, data: { confirm: "确定删除？" } %>
          <% end %>

          <dl>
            <dt><%= avatar_tag @topic_user %><p><%= @topic_user.name %></p></dt>
            <dd class="post-name">
              <span><%= link_to @topic.title, '#'%></span>
              <span class="tag-top">置顶</span>
              <span class="tag-new">NEW</span>
              <span class="tag-best">精华</span>
              <span class="tag-mark">
                <%= image_tag "mark.gif" %>
              </span>
            </dd>
            <dd class="post-info">
              <span><%= @topic.user.name %></span><var>·</var>
              <span><%= format_datetime(@topic.created_at) %></span>
              <var>·</var>
              <span><%= @topic.node.title %></span><var>·</var>
              <span><%= @topic.views.to_i %>浏览</span><var>·</var>
              <span><%= @topic.comments_count %>回复</span>
            </dd>
            <dd class="con">
              <%= raw @topic.body %>
            </dd>
            <dd class="share-to">
              <ul class="share-btn">
                <li>分享到：</li>
                <%= social_share_button_tag(@topic.title, url: request.fullpath) %>
                <li class="inform"><a>举报</a></li>
              </ul>
              <ul class="reply-btn">
                <li>
                  <% if @topic.liked_by? current_user %>
                    <%= link_to "取消收藏", topic_like_path(@topic), method: :delete %></li>
                  <% else %>
                    <%= link_to "收藏", topic_like_path(@topic), method: :post %></li>
                  <% end %>
                <li><%= image_tag "msg.png" %>回复</li>
              </ul>
            </dd>
          </dl>
          <dl class="reply-list">
            <p class="storey sofa">沙发</p>
            <% if @first_comment.present? %>
              <% if can? :trash, @first_comment %>
                <%= link_to "删除评论", trash_comment_path(@first_comment), method: :delete, data: { confirm: "确定删除？" } %>
              <% end %>
              <dt>
                <%= avatar_tag @first_comment.user %>
                <p><%= @first_comment.user.name %></p>
              </dt>
              <dd>
                <p class="time">
                  <%= format_datetime(@first_comment.created_at) %>
                </p>
                <p><%= raw @first_comment.body %></p>
              </dd>
              <dd class="reply-con">
                <div class="top-btn">
                  <span class="inform">举报</span>
                  <ul class="add-btn">
                    <li>
                      <% if @first_comment.liked_by? current_user %>
                        <%= link_to "取消收藏", comment_like_path(@first_comment), method: :delete %>
                      <% else %>
                        <%= link_to "收藏", comment_like_path(@first_comment), method: :post %>
                      <% end %>
                    </li>
                    <li>回复</li>
                  </ul>
                </div>

                <div class="reply hidden">
                  <dl>
                    <dt><%= avatar_tag current_user.avatar if current_user %></dt>
                    <dd>
                      <p class="username">冯玉玉Caroline</p>
                      <p>使在线学习者的学习体验得到质的飞跃。升级后的课程以最高质量带给用户极致的用户体验，提升平均时间的信息量的传递，让教育变得更有趣，更有信息量。学习者满足了视听享受，也就更有动力完成更多的课程。</p>
                      <p class="time">
                        <span>2014-09-12 16:00</span>
                        <span>举报</span>
                      </p>
                      <p class="reply-btn">回复</p>
                    </dd>
                  </dl>
                  <div class="reply-textarea">
                    <div class="top-btn">
                      <p class="others">
                        <span>还有剩余13条回复，</span>
                        <a class="click" href="">点击查看</a>
                      </p>
                      <p class="reply-host">提交回复</p>
                    </div>
                    <div class="textarea">
                      <textarea name="" id=""></textarea>
                      <p class="reply-btn" type="submit">回复楼主</p>
                    </div>
                  </div>
                </div>
              </dd>
            <% end %>
          </dl>
          <div class="inform-bac hidden"></div>
          <div class="inform-con hidden">
            <h3>我要举报</h3>
            <dl>
              <dt>
                <span class="username">用户名</span>
                <span>所发布的</span>
                <p>帖子名称</p>
              </dt>
              <dd>
                <p>举报原因</p>
                <textarea name="" id="" cols="30" rows="10"></textarea>
                <div class="btn">
                  <span>提交举报</span>
                  <span>取消举报</span>
                </div>
              </dd>
            </dl>
          </div>
        </div>
        <div class="post-reply">
          <dl>
            <dt>
              <%= avatar_tag current_user if current_user %>
              <p><%= current_user.name if current_user %></p>
            </dt>
            <dd>
              <%= render 'comments/new_comment', commentable: @topic %>
            </dd>
          </dl>
        </div>
      </div>
      <div class="right">
        <%= render "/shared/search" %>
        <%= render "shared/topic_right" %>
      </div>
    </div>