config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  get 'home/welcome'
  get 'login',     to: 'sessions#new', as: 'login'
  get 'service',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount Simditor::Engine => '/simditor'

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :topics
      get :comments
      get :notifications
    end
  end

  resources :nodes

  resources :topics, concerns: [:likeable] do
    get :search, on: :collection
    delete :trash, on: :member
  end

  resources :comments, concerns: [:likeable] do
    delete :trash, on: :member
  end

  root "home#welcome"

  draw :admin
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
    @nodes = Node.list
    @title_list = @nodes.pluck(:title)
    @sliders = Ad.where(:ad_type => "carousel")
    @topics = Topic.order("level DESC, created_at DESC").page(params[:page])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/welcome.html.erb
<link rel="stylesheet" href="/kkb/index.css">

    <div class="main">
      <div class="left">
        <div class="slider">
          <a href="">
            <%= image_tag "slider1.jpg", class: "show" %>
            <p class="description">
              <span>帖子 名称</span>
              <span>用户名·学习小组·276浏览·62回复</span>
            </p>
          </a>
          <ul class="slider-tag">
            <% @sliders.each do |slider|%>
            <li> <%= image_tag slider.image_url %> </li>
            <% end %>
          </ul>
        </div>
        <div class="post-list">
          <div class="title">
            <h3>全部帖子</h3>
            <ul class="tags">
              <li>
                <%= link_to "精品帖子", topics_path(:level => 3)%>
              </li>
              <li>
                <%= link_to "热门帖子", topics_path(:level => 2)%>
              </li>
              <li>
                <%= link_to "最新帖子", topics_path %>
              </li>
            </ul>
          </div>
          <div class="best list">
            <%= render "/shared/topic_list", collection: @topics %>
          </div>
        </div>
        <div class="page">
          <%= paginate @topics %>
        </div>
      </div>
      <div class="right">
        <%= render "/shared/search" %>

        <div class="topic">
          <h2>社区话题</h2>
          <ul class="topic-tag">
            <% Node.list.each do |node| %>
              <li><%= link_to "#{node.title}(#{node.topics.count})", topics_path(node_id: node.id) %></li>
            <% end %>
          </ul>
        </div>
        <div class="share">
          <%= render '/shared/resource_node' %>
        </div>
        <div class="ad-img">
          <%= image_tag "mouse.jpg" %>
          <%= image_tag "mouse.jpg" %>
          <%= image_tag "mouse.jpg" %>
        </div>
      </div>
      <div class="sidebar">
        <dl>
          <dt>
            <a href="/">
              <%= image_tag "novice_help.png" %>
            </a>
          </dt>
          <dd>新手帮助</dd>
        </dl>
        <dl>
          <dt>
            <a href="">
              <%= image_tag "globle_feedback.png" %>
            </a>
          </dt>
          <dd>意见反馈</dd>
        </dl>
        <dl>
          <dt>
            <a href="/">
              <%= image_tag "return_to_top.png" %>
            </a>
          </dt>
          <dd>返回顶部</dd>
        </dl>
      </div>
    </div>